apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: node-app-secrets
  namespace: dev
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: node-app-secret
    creationPolicy: Owner
  data:
  - secretKey: MONGO_URL
    remoteRef:
      key: arn:aws:secretsmanager:us-east-1:123456789012:secret:dev/mongo#MONGO_URL
