apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        fsGroup: 1000
      containers:
        - name: node
          image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/devsecops-eval:${IMAGE_TAG}
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: node-app-secret
                  key: MONGO_URL
            - name: MONGO_DB
              value: devsecops_db
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      imagePullSecrets:
        - name: ecr-registry-secret
