name: CI/CD Security Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/devsecops-eval-api
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install
        run: npm ci
        working-directory: ./app

      - name: Static analysis (Semgrep)
        uses: returntocorp/semgrep-action@v2
        with:
          config: "p/ci"  # example, tune rules
        continue-on-error: false

      - name: Build container image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG ./app
        env: DOCKER_BUILDKIT: 1

      - name: Trivy image scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          exit-code: '1'             # non-zero exit on vuln thresholds
          severity: CRITICAL,HIGH

      - name: Push image (only if security gates passed)
        if: ${{ success() }}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest
